part of 'index_theme.dart';

final ThemeData themeBlue = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xff3f51b5),
  primaryColorLight: const Color(0xff9fa8da),
  primaryColorDark: const Color(0xff303f9f),
  canvasColor: const Color(0xfff3f4f6),
  scaffoldBackgroundColor: const Color(0xfff8fafc),
  cardColor: const Color(0xffffffff),
  dividerColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  splashColor: const Color(0x66c8c8c8),
  unselectedWidgetColor: const Color(0x8a000000),
  disabledColor: const Color(0x61000000),
  secondaryHeaderColor: const Color(0xffe8eaf6),
  textSelectionTheme: const TextSelectionThemeData(
    selectionColor: Color(0xff9fa8da),
    cursorColor: Color(0xff3f51b5),
    selectionHandleColor: Color(0xff7986cb),
  ),
  hintColor: const Color(0x8a000000),
  colorScheme: const ColorScheme.light(
    primary: Color(0xff3f51b5),
    primaryContainer: Color(0xff303f9f),
    secondary: Color(0xff5c6bc0),
    secondaryContainer: Color(0xff3f51b5),
    surface: Color(0xffffffff),
    error: Color(0xffd32f2f),
    onPrimary: Color(0xffffffff),
    onSecondary: Color(0xffffffff),
    onSurface: Color(0xff1a1a1a),
    onError: Color(0xffffffff),
    brightness: Brightness.light,
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xff3f51b5),
    foregroundColor: Color(0xffffffff),
    elevation: 2,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Color(0xff1a1a1a)),
    displayMedium: TextStyle(color: Color(0xff1a1a1a)),
    displaySmall: TextStyle(color: Color(0xff1a1a1a)),
    headlineLarge: TextStyle(color: Color(0xff1a1a1a)),
    headlineMedium: TextStyle(color: Color(0xff1a1a1a)),
    headlineSmall: TextStyle(color: Color(0xff1a1a1a)),
    titleLarge: TextStyle(color: Color(0xff1a1a1a)),
    titleMedium: TextStyle(color: Color(0xff1a1a1a)),
    titleSmall: TextStyle(color: Color(0xff1a1a1a)),
    bodyLarge: TextStyle(color: Color(0xff1a1a1a)),
    bodyMedium: TextStyle(color: Color(0xff1a1a1a)),
    bodySmall: TextStyle(color: Color(0x8a000000)),
    labelLarge: TextStyle(color: Color(0xff1a1a1a)),
    labelMedium: TextStyle(color: Color(0xff1a1a1a)),
    labelSmall: TextStyle(color: Color(0xff1a1a1a)),
  ),
);
