part of 'index_theme.dart';

final ThemeData themeDark = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xff1976d2),
  primaryColorLight: const Color(0xff42a5f5),
  primaryColorDark: const Color(0xff0d47a1),
  canvasColor: const Color(0xff121212),
  scaffoldBackgroundColor: const Color(0xff121212),
  cardColor: const Color(0xff1e1e1e),
  dividerColor: const Color(0x1fffffff),
  highlightColor: const Color(0x40cccccc),
  splashColor: const Color(0x40cccccc),
  unselectedWidgetColor: const Color(0xb3ffffff),
  disabledColor: const Color(0x62ffffff),
  secondaryHeaderColor: const Color(0xff263238),
  textSelectionTheme: const TextSelectionThemeData(
    selectionColor: Color(0xff64b5f6),
    cursorColor: Color(0xff2196f3),
    selectionHandleColor: Color(0xff42a5f5),
  ),
  hintColor: const Color(0xb3ffffff),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xff2196f3),
    primaryContainer: Color(0xff1976d2),
    secondary: Color(0xff03dac6),
    secondaryContainer: Color(0xff018786),
    surface: Color(0xff1e1e1e),
    error: Color(0xffcf6679),
    onPrimary: Color(0xff000000),
    onSecondary: Color(0xff000000),
    onSurface: Color(0xffffffff),
    onError: Color(0xff000000),
    brightness: Brightness.dark,
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xff1e1e1e),
    foregroundColor: Color(0xffffffff),
    elevation: 0,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Color(0xffffffff)),
    displayMedium: TextStyle(color: Color(0xffffffff)),
    displaySmall: TextStyle(color: Color(0xffffffff)),
    headlineLarge: TextStyle(color: Color(0xffffffff)),
    headlineMedium: TextStyle(color: Color(0xffffffff)),
    headlineSmall: TextStyle(color: Color(0xffffffff)),
    titleLarge: TextStyle(color: Color(0xffffffff)),
    titleMedium: TextStyle(color: Color(0xffffffff)),
    titleSmall: TextStyle(color: Color(0xffffffff)),
    bodyLarge: TextStyle(color: Color(0xffffffff)),
    bodyMedium: TextStyle(color: Color(0xffffffff)),
    bodySmall: TextStyle(color: Color(0xb3ffffff)),
    labelLarge: TextStyle(color: Color(0xffffffff)),
    labelMedium: TextStyle(color: Color(0xffffffff)),
    labelSmall: TextStyle(color: Color(0xffffffff)),
  ),
);
